### ISSUE TITLE
Simpler Titles for Articles in Documentation

### ISSUE THREAD

**Issue by minoobeyzavi** [minoobeyzavi/Visual-KPI#5]
Most titles can be simpler, more standard or more friendly to seem more familiar and easy to understand at first sight to everyone. They should also be more focused on the main goal of each article which is either to introduce a Visual KPI feature or to provide instructions. Numbering would also help create a simple map of thoughts and questions in the readers' mind.

Example:

General & Pre-Sales
Interfaces & Data Sources
Installation
Visual KPI Server (administration)
Visual KPI Designer (Configuration)
Remote Context Service
User Guide
Security
Questions & Answers (FAQ)

**1. What is Visual KPI?
2. Interface with Data Sources
3. Installation
4. Visual KPI Server
5. Designer Configurations
6. Remote Context Services
7. Dashboard & Notifications
8. Security
9. FAQ**

**Comment by rhylton** [comment]
I agree these need improvement, but would probably go with something like the following (I'm not yet confident in the order of the topics, but that can easily be changed at any time):

1. What is Visual KPI? (Overview & Pre-Sales)
2. Installation & Upgrades
3. Visual KPI User Guides
4. Visual KPI Server (Admin)
5. Interfaces & Data Sources
6. Visual KPI Designer (Configuration)
7. Remote Context Service (External Metadata)
8. Security
9. FAQ
